UPSTREAM_DNS_PORT = 53
MAX_RECEIVED_DNS_MESSAGE_SIZE = 4096
MAX_CLIENT_DNS_RESPONSE_SIZE = 512

MAX_OUTBOUND_ATTEMPTS = 50
MAX_REFERRAL_LEVELS = 10
MAX_CNAME_RECORDS = 10
MAX_RESOLUTION_SECONDS = 30

TYPE_A = 1
TYPE_NS = 2
TYPE_CNAME = 5
TYPE_PTR = 12
TYPE_MX = 15

CLASS_IN = 1

RCODE_NOERROR = 0
RCODE_FORMERR = 1
RCODE_SERVFAIL = 2
RCODE_NXDOMAIN = 3
RCODE_REFUSED = 5

SUPPORTED_QUERY_TYPES = {
    TYPE_A,
    TYPE_NS,
    TYPE_CNAME,
    TYPE_PTR,
    TYPE_MX,
}

ENCODABLE_RECORD_TYPES = {
    TYPE_A,
    TYPE_NS,
    TYPE_CNAME,
    TYPE_PTR,
    TYPE_MX,
}
